# -*- coding: utf-8 -*-
"""webscrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oMWF5vHlM6jXHC744AG6S8qW4CAtYOts
"""

pip install autoscraper # it's a package for doing web scrapping

from autoscraper import AutoScraper #from the above package i have called the sub package AutoScraper

"""flipkart_url **the url link which you want to do web scrapping**

wanted_list= **the thing you want in web scrapping here i want price and the details**




"""

flipkart_url="https://www.flipkart.com/search?q=sarees&sid=clo%2C8on%2Czpd%2C9og&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_3_na_na_na&as-pos=1&as-type=RECENT&suggestionId=sarees%7CWomen%27s+Sarees&requestId=f241db9f-4db4-4a97-b803-20e7e99d7723&as-backfill=on"
wanted_list=['Printed Kanjivaram Cotton Silk Saree','₹249']

scraper=AutoScraper() # i have saved the sub package in the scraper variable

result=scraper.build(flipkart_url,wanted_list) #putting the url and wanted list in the scraper build

print(result) #all the title and price will be shown

scraper.get_result_similar(amazon_url,grouped=True) #this is done for finding the key value pair of price and title here grouped should be true to find the key value pair

"""**remember to put the key value from the above code the key value is the criedential you want for web scrapoing and everytime you run the code the ke value will change and putting the value according to the key value herer it's title and price**"""

scraper.set_rule_aliases({'rule_i94t':'Title', 'rule_11yj':'Price'}) # rule_i94t , rule_11yj are the key value

scraper.save('flipkart_search') # saving the scraper

"""**for automating the scrapper we usedd the below code and paste the url whom we want to do scrapping **





"""

result=scraper.get_result_similar('https://www.flipkart.com/search?q=nike%20shoes&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off',group_by_alias=True)

result['Price'] #price of all the nike product

